<?php

declare(strict_types=1);

namespace App\Services\VideoExtraction;

use Illuminate\Support\Facades\Log;

/**
 * Service for generating stable, hash-based filenames for video downloads.
 *
 * This service ensures consistent naming regardless of video title changes
 * and provides utilities for filename management.
 */
class FilenameService
{
    /**
     * Generate a stable filename based on URL, format, and session parameters.
     *
     * @param  string  $originUrl  The original video URL
     * @param  string  $cdnId  The CDN format ID
     * @param  string|null  $downloadSessionId  Optional download session ID
     * @param  bool  $includeTimestamp  Whether to include timestamp for uniqueness
     * @return string Stable filename template for yt-dlp
     */
    public function generateStableFilename(
        string $originUrl,
        string $cdnId,
        ?string $downloadSessionId = null,
        bool $includeTimestamp = true
    ): string {
        // Create a unique identifier based on URL, format, and session
        $hashInput = $this->normalizeUrl($originUrl).'|'.$cdnId;

        if ($downloadSessionId) {
            $hashInput .= '|'.$downloadSessionId;
        }

        // Generate a short, stable hash
        $hash = substr(hash('sha256', $hashInput), 0, 16);

        // Add timestamp for additional uniqueness if requested
        $filename = $hash;
        if ($includeTimestamp) {
            $timestamp = now()->format('Ymd_His');
            $filename .= "_{$timestamp}";
        }

        Log::debug('Generated stable filename', [
            'origin_url' => $originUrl,
            'cdn_id' => $cdnId,
            'download_session_id' => $downloadSessionId,
            'hash_input' => $hashInput,
            'generated_hash' => $hash,
            'filename' => $filename,
        ]);

        // Return filename template that yt-dlp will use
        return "{$filename}.%(ext)s";
    }

    /**
     * Generate a content-based hash for duplicate detection.
     * This hash is based only on URL and format, ignoring timestamps.
     *
     * @param  string  $originUrl  The original video URL
     * @param  string  $cdnId  The CDN format ID
     * @return string Content hash for duplicate detection
     */
    public function generateContentHash(string $originUrl, string $cdnId): string
    {
        $hashInput = $this->normalizeUrl($originUrl).'|'.$cdnId;

        return substr(hash('sha256', $hashInput), 0, 16);
    }

    /**
     * Extract hash from a filename generated by this service.
     *
     * @param  string  $filename  The filename to extract hash from
     * @return string|null The extracted hash or null if not found
     */
    public function extractHashFromFilename(string $filename): ?string
    {
        // Remove extension first
        $nameWithoutExt = pathinfo($filename, PATHINFO_FILENAME);

        // Pattern: hash_timestamp or just hash
        if (preg_match('/^([a-f0-9]{16})(?:_\d{8}_\d{6})?$/', $nameWithoutExt, $matches)) {
            return $matches[1];
        }

        return null;
    }

    /**
     * Check if a filename was generated by this service.
     *
     * @param  string  $filename  The filename to check
     * @return bool True if filename follows our hash-based pattern
     */
    public function isHashBasedFilename(string $filename): bool
    {
        return $this->extractHashFromFilename($filename) !== null;
    }

    /**
     * Generate a human-readable filename from video metadata.
     * This is used for display purposes, not for actual file storage.
     *
     * @param  array  $metadata  Video metadata
     * @param  string  $extension  File extension
     * @param  int  $maxLength  Maximum filename length
     * @return string Human-readable filename
     */
    public function generateDisplayFilename(array $metadata, string $extension, int $maxLength = 100): string
    {
        $title = $metadata['title'] ?? 'video';
        $author = $metadata['uploader'] ?? null;

        // Clean title for filename use
        $cleanTitle = $this->sanitizeForFilename($title);

        // Add author if available and space permits
        if ($author && strlen($cleanTitle) < $maxLength - 20) {
            $cleanAuthor = $this->sanitizeForFilename($author);
            $cleanTitle = "{$cleanAuthor} - {$cleanTitle}";
        }

        // Truncate if too long
        if (strlen($cleanTitle) > $maxLength - strlen($extension) - 1) {
            $cleanTitle = substr($cleanTitle, 0, $maxLength - strlen($extension) - 4).'...';
        }

        return "{$cleanTitle}.{$extension}";
    }

    /**
     * Normalize URL for consistent hashing.
     * Removes query parameters that don't affect content.
     *
     * @param  string  $url  The URL to normalize
     * @return string Normalized URL
     */
    private function normalizeUrl(string $url): string
    {
        $parsed = parse_url($url);

        if (! $parsed) {
            return $url;
        }

        // Rebuild URL without certain query parameters
        $normalized = $parsed['scheme'].'://'.$parsed['host'];

        if (isset($parsed['port'])) {
            $normalized .= ':'.$parsed['port'];
        }

        if (isset($parsed['path'])) {
            $normalized .= $parsed['path'];
        }

        // For some platforms, preserve important query parameters
        if (isset($parsed['query'])) {
            parse_str($parsed['query'], $queryParams);

            // Keep only content-relevant parameters
            $keepParams = [];
            foreach (['v', 'video_id', 'p', 'reel'] as $param) {
                if (isset($queryParams[$param])) {
                    $keepParams[$param] = $queryParams[$param];
                }
            }

            if (! empty($keepParams)) {
                $normalized .= '?'.http_build_query($keepParams);
            }
        }

        return $normalized;
    }

    /**
     * Sanitize string for use in filenames.
     *
     * @param  string  $string  The string to sanitize
     * @return string Sanitized string
     */
    private function sanitizeForFilename(string $string): string
    {
        // Remove or replace problematic characters
        $sanitized = preg_replace('/[^\w\s\-_\.]/', '', $string);

        // Replace multiple spaces/underscores with single ones
        $sanitized = preg_replace('/[\s_]+/', '_', $sanitized);

        // Remove leading/trailing underscores and dots
        $sanitized = trim($sanitized, '_.');

        return $sanitized ?: 'video';
    }
}
