[program:laravel-schedule]
process_name=%(program_name)s
command=/usr/bin/php /var/www/social-downloader/artisan schedule:work
autostart=true
autorestart=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/social-downloader/storage/logs/schedule.log
stopwaitsecs=3600
