[program:social-downloader-laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=/usr/bin/php /var/www/social-downloader/artisan queue:work --queue=priority,basic,default,guest,validation --sleep=3 --tries=3
autostart=true
autorestart=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/social-downloader/storage/logs/worker.log
